[package]
name = "creamui-widgets"
description = "Headless and themed widgets built on creamui-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
readme = "README.md"
keywords = ["gui", "ui", "widgets", "desktop"]
categories = ["gui"]

[dependencies]
creamui-core = { workspace = true }
creamui-theme = { workspace = true }
creamui-fonts = { workspace = true }
creamui-reactive = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
arboard = { workspace = true }
rfd = { workspace = true }
