[package]
name = "showcase"
publish = false
version.workspace = true
edition.workspace = true

[dependencies]
creamui-core = { workspace = true }
creamui-devtools = { workspace = true, features = ["perf-metrics"] }
creamui-image = { path = "../../crates/image", features = ["jpeg", "webp"] }
creamui-jsx = { workspace = true }
creamui-macros = { workspace = true }
creamui-reactive = { workspace = true }
creamui-render = { workspace = true }
creamui-theme = { workspace = true }
creamui-widgets = { workspace = true }
