[package]
name = "showcase"
publish = false
version.workspace = true
edition.workspace = true

[features]
default = ["platform-winit"]
platform-winit = ["creamui-render/platform-winit"]
platform-android = ["creamui-render/platform-android"]

[dependencies]
creamui-core = { workspace = true }
creamui-devtools = { workspace = true, features = ["perf-metrics"] }
creamui-image = { path = "../../crates/image", features = ["jpeg", "webp"] }
creamui-jsx = { workspace = true }
creamui-macros = { workspace = true }
creamui-reactive = { workspace = true }
creamui-render = { version = "0.2.0", path = "../../crates/render", default-features = false }
creamui-theme = { workspace = true }
creamui-widgets = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
android-activity = { version = "0.6", features = ["native-activity"] }
