[package]
name = "creamui"
description = "The main CreamUI crate: native reactive desktop UI for Rust"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
readme = "README.md"
keywords = ["gui", "ui", "desktop", "native"]
categories = ["gui"]

[features]
default = []
image = ["dep:creamui-image"]
image-jpeg = ["image", "creamui-image/jpeg"]
image-webp = ["image", "creamui-image/webp"]
jsx = ["dep:creamui-jsx", "dep:creamui-macros"]
abi = ["dep:creamui-abi"]
dynamic = ["abi", "jsx", "dep:creamui-dynamic"]
ffi = ["abi", "dep:creamui_ffi"]
devtools = ["dep:creamui-devtools"]
tray = ["creamui-render/tray"]
platform-wayland = ["creamui-platform/wayland", "creamui-render/platform-wayland"]
platform-x11 = ["creamui-platform/x11", "creamui-render/platform-x11"]
platform-windows = ["creamui-platform/windows", "creamui-render/platform-windows"]
full = ["image-jpeg", "image-webp", "jsx", "dynamic", "ffi", "devtools", "tray"]

[dependencies]
creamui-core = { workspace = true }
creamui-reactive = { workspace = true }
creamui-platform = { workspace = true }
creamui-render = { workspace = true }
creamui-devtools = { workspace = true, optional = true }
creamui-theme = { workspace = true }
creamui-fonts = { workspace = true }
creamui-widgets = { workspace = true }
creamui-image = { workspace = true, optional = true }
creamui-jsx = { workspace = true, optional = true }
creamui-macros = { workspace = true, optional = true }
creamui-abi = { workspace = true, optional = true }
creamui-dynamic = { workspace = true, optional = true }
creamui_ffi = { package = "creamui-ffi", version = "0.1.1", path = "../ffi", optional = true }
