[package]
name = "creamui-theme-loader"
description = "System theme discovery and appearance loading for CreamUI"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[dependencies]
creamui-theme = { version = "0.1.2", path = "../theme" }
serde = { version = "1", features = ["derive"] }
toml = "0.9"
