[package]
name = "creamui-browser-bridge-tests"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
creamui-widgets = { path = "../.." }
creamui-core = { path = "../../../core" }
creamui-reactive = { path = "../../../reactive" }
creamui-theme = { path = "../../../theme" }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
