[package]
name = "creamui-macros"
description = "JSX syntax for CreamUI's Rust widget builders"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
readme = "README.md"
keywords = ["jsx", "gui", "ui", "widgets"]
categories = ["gui"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
proc-macro-crate = "3"
creamui-core = { workspace = true }

[dev-dependencies]
creamui-core = { workspace = true }
creamui-dynamic = { workspace = true }
creamui-image = { workspace = true }
creamui-jsx = { workspace = true }
creamui-reactive = { workspace = true }
creamui-theme = { workspace = true }
creamui-widgets = { workspace = true }
