[package]
name = "creamui-showcase-web"
publish = false
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
showcase = { path = "../../examples/showcase" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
creamui-fonts = { workspace = true }
